import {
  Activity,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BarChart3,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  Code2,
  Command,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileCode2,
  FileText,
  Flame,
  Github,
  Globe2,
  GraduationCap,
  Hand,
  Heart,
  Info,
  Layers3,
  Leaf,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Moon,
  Network,
  Orbit,
  PanelTop,
  PenLine,
  Phone,
  Play,
  Plus,
  Search,
  Send,
  Server,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Upload,
  X,
  Zap,
} from 'lucide-react';
import type { SVGProps } from 'react';
import type { LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-down': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  chart: BarChart3,
  book: BookOpen,
  orcid: BookOpen,
  scholar: BookOpen,
  table: Layers3,
  scan: Eye,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  user: CircleUserRound,
  code: Code2,
  command: Command,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  external: ExternalLink,
  eye: Eye,
  file: FileText,
  'file-code': FileCode2,
  flame: Flame,
  github: Github,
  globe: Globe2,
  graduation: GraduationCap,
  hand: Hand,
  heart: Heart,
  info: Info,
  layers: Layers3,
  leaf: Leaf,
  linkedin: Linkedin,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  message: MessageCircle,
  moon: Moon,
  network: Network,
  workflow: Network,
  orbit: Orbit,
  panel: PanelTop,
  pen: PenLine,
  phone: Phone,
  play: Play,
  plus: Plus,
  search: Search,
  send: Send,
  server: Server,
  share: Share2,
  shield: ShieldCheck,
  spark: Sparkles,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  upload: Upload,
  x: X,
  zap: Zap,
};

export function Icon({
  name,
  size = 18,
  strokeWidth = 1.8,
  ...props
}: { name: string; size?: number; strokeWidth?: number } & SVGProps<SVGSVGElement>) {
  const Component = iconMap[name] ?? Sparkles;
  return <Component size={size} strokeWidth={strokeWidth} {...props} />;
}
